<?php

namespace Database\Seeders;

use App\Models\UnitKerja;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UnitKerjaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['id' => 1,  'kode_unit_kerja' => 'A',   'nama_unit_kerja' => 'Keguruan dan Ilmu Pendidikan',         'jenis_unit_kerja' => 'Fakultas', 'jenjang' => null, 'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2,  'kode_unit_kerja' => 'A1A', 'nama_unit_kerja' => 'Pendidikan Bahasa Indonesia',           'jenis_unit_kerja' => 'prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3,  'kode_unit_kerja' => 'A1B', 'nama_unit_kerja' => 'Pendidikan Bahasa Inggris',             'jenis_unit_kerja' => 'prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4,  'kode_unit_kerja' => 'A1C', 'nama_unit_kerja' => 'Pendidikan Matematika',                 'jenis_unit_kerja' => 'prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5,  'kode_unit_kerja' => 'A1D', 'nama_unit_kerja' => 'Pendidikan Biologi',                    'jenis_unit_kerja' => 'prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6,  'kode_unit_kerja' => 'A1E', 'nama_unit_kerja' => 'Pendidikan Fisika',                     'jenis_unit_kerja' => 'prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7,  'kode_unit_kerja' => 'A1F', 'nama_unit_kerja' => 'Pendidikan Kimia',                      'jenis_unit_kerja' => 'prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8,  'kode_unit_kerja' => 'A1G', 'nama_unit_kerja' => 'Pendidikan Guru Sekolah Dasar',         'jenis_unit_kerja' => 'prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 9,  'kode_unit_kerja' => 'A1I', 'nama_unit_kerja' => 'Pendidikan Guru Paud',                  'jenis_unit_kerja' => 'prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 10, 'kode_unit_kerja' => 'A1J', 'nama_unit_kerja' => 'Pendidikan Non Formal',                 'jenis_unit_kerja' => 'prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 11, 'kode_unit_kerja' => 'A1L', 'nama_unit_kerja' => 'Bimbingan dan Konseling',               'jenis_unit_kerja' => 'prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            [
                'id' => 12,
                'kode_unit_kerja' => 'A1M',
                'nama_unit_kerja' => 'Pendidikan Jasmani',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:38:11',
                'updated_at' => '2021-07-12 16:38:11',
            ],
            [
                'id' => 13,
                'kode_unit_kerja' => 'A1N',
                'nama_unit_kerja' => 'Pendidikan IPA',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:40:43',
                'updated_at' => '2021-07-12 16:40:43',
            ],
            [
                'id' => 14,
                'kode_unit_kerja' => 'A01',
                'nama_unit_kerja' => 'Bahasa Inggris',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'D3',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:45:10',
                'updated_at' => '2021-07-12 16:45:10',
            ],
            [
                'id' => 53,
                'kode_unit_kerja' => 'A2A',
                'nama_unit_kerja' => 'Pendidikan Bahasa Indonesia',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:46:41',
                'updated_at' => '2021-07-12 16:46:41',
            ],
            [
                'id' => 54,
                'kode_unit_kerja' => 'A2B',
                'nama_unit_kerja' => 'Teknologi Pendidikan',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:47:08',
                'updated_at' => '2021-07-12 16:47:08',
            ],
            [
                'id' => 55,
                'kode_unit_kerja' => 'A2C',
                'nama_unit_kerja' => 'Pendidikan Dasar',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:47:33',
                'updated_at' => '2021-07-12 16:47:33',
            ],
            [
                'id' => 56,
                'kode_unit_kerja' => 'A2D',
                'nama_unit_kerja' => 'Administrasi Pendidikan',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:47:57',
                'updated_at' => '2021-07-12 16:47:57',
            ],
            [
                'id' => 57,
                'kode_unit_kerja' => 'A2E',
                'nama_unit_kerja' => 'Pendidikan Bahasa Inggris',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:48:25',
                'updated_at' => '2021-07-12 16:48:25',
            ],
            [
                'id' => 58,
                'kode_unit_kerja' => 'A2F',
                'nama_unit_kerja' => 'Pendidikan Matematika',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:48:57',
                'updated_at' => '2021-07-12 16:48:57',
            ],
            [
                'id' => 59,
                'kode_unit_kerja' => 'A2G',
                'nama_unit_kerja' => 'Pendidikan IPA',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:49:18',
                'updated_at' => '2021-07-12 16:49:18',
            ],
            [
                'kode_asal' => 'A3',
                'nama_asal' => 'S3 LINGUISTIK TERAPAN',
                'jenis' => 'Prodi',
                'created_at' => '2023-10-23 19:11:45',
                'updated_at' => '2023-10-23 19:11:45',
            ],
            [
                'id' => 60,
                'kode_unit_kerja' => 'A3A',
                'nama_unit_kerja' => 'Pendidikan',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S3',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:49:38',
                'updated_at' => '2021-07-12 16:49:38',
            ],

            [
                'kode_asal' => 'A4A',
                'nama_asal' => 'PROFESI PENDIDIKAN PROFESI GURU',
                'jenis' => 'Prodi',
                'created_at' => '2023-02-21 03:29:00',
                'updated_at' => '2023-02-21 03:29:00',
            ],
            [
                'id' => 61,
                'kode_unit_kerja' => 'B2A',
                'nama_unit_kerja' => 'Ilmu Hukum',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Hukum',
                'created_at' => '2021-07-13 10:47:34',
                'updated_at' => '2021-07-13 10:47:34',
            ],
            [
                'id' => 62,
                'kode_unit_kerja' => 'B2B',
                'nama_unit_kerja' => 'Kenotariatan',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Hukum',
                'created_at' => '2021-07-13 10:47:54',
                'updated_at' => '2021-07-13 10:47:54',
            ],

            [
                'id' => 12,
                'kode_unit_kerja' => 'C',
                'nama_unit_kerja' => 'Ekonomi Dan Bisnis',
                'jenis_unit_kerja' => 'Fakultas',
                'jenjang' => null,
                'fakultas' => 'Fakultas Ekonomi dan Bisnis',
                'created_at' => '2021-06-16 17:11:25',
                'updated_at' => '2021-06-16 17:11:25',
            ],
            [
                'id' => 13,
                'kode_unit_kerja' => 'C1A',
                'nama_unit_kerja' => 'Ekonomi Pembangunan',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ekonomi dan Bisnis',
                'created_at' => '2021-06-16 17:18:58',
                'updated_at' => '2021-06-16 17:18:58',
            ],
            [
                'id' => 14,
                'kode_unit_kerja' => 'C1B',
                'nama_unit_kerja' => 'Manajemen',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ekonomi dan Bisnis',
                'created_at' => '2021-06-16 17:04:35',
                'updated_at' => '2021-06-16 17:04:35',
            ],
            [
                'id' => 15,
                'kode_unit_kerja' => 'C1C',
                'nama_unit_kerja' => 'Akuntansi',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ekonomi dan Bisnis',
                'created_at' => '2021-06-16 16:57:20',
                'updated_at' => '2021-06-16 16:57:20',
            ],
            [
                'id' => 63,
                'kode_unit_kerja' => 'C0A',
                'nama_unit_kerja' => 'Akuntansi',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'D3',
                'fakultas' => 'Fakultas Ekonomi',
                'created_at' => '2021-07-13 10:51:44',
                'updated_at' => '2021-07-13 10:51:44',
            ],
            [
                'id' => 64,
                'kode_unit_kerja' => 'C2A',
                'nama_unit_kerja' => 'Ekonomi Terapan',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Ekonomi',
                'created_at' => '2021-07-13 10:52:16',
                'updated_at' => '2023-02-21 03:25:10',
            ],
            [
                'id' => 65,
                'kode_unit_kerja' => 'C2B',
                'nama_unit_kerja' => 'Manajemen',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Ekonomi',
                'created_at' => '2021-07-13 10:52:34',
                'updated_at' => '2021-07-13 10:52:34',
            ],
            [
                'id' => 66,
                'kode_unit_kerja' => 'C2C',
                'nama_unit_kerja' => 'Akuntansi',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Ekonomi',
                'created_at' => '2021-07-13 10:52:52',
                'updated_at' => '2021-07-13 10:52:52',
            ],
            [
                'id' => 67,
                'kode_unit_kerja' => 'C3A',
                'nama_unit_kerja' => 'Ilmu Ekonomi',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S3',
                'fakultas' => 'Fakultas Ekonomi',
                'created_at' => '2021-07-13 10:53:14',
                'updated_at' => '2023-02-21 03:21:16',
            ],
            [
                'id' => 68,
                'kode_unit_kerja' => 'C3B',
                'nama_unit_kerja' => 'Ilmu Manajemen',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S3',
                'fakultas' => 'Fakultas Ekonomi',
                'created_at' => '2021-07-13 10:53:30',
                'updated_at' => '2023-02-21 03:21:43',
            ],

            [
                'id' => 16,
                'kode_unit_kerja' => 'D',
                'nama_unit_kerja' => 'Ilmu Sosial Dan Politik',
                'jenis_unit_kerja' => 'Fakultas',
                'jenjang' => null,
                'fakultas' => 'Fakultas Ilmu Sosial dan Politik',
                'created_at' => '2021-06-16 17:12:59',
                'updated_at' => '2021-06-16 17:12:59',
            ],
            [
                'id' => 17,
                'kode_unit_kerja' => 'D1A',
                'nama_unit_kerja' => 'Ilmu Kesejahteraan Sosial',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ilmu Sosial dan Politik',
                'created_at' => '2021-06-16 17:23:10',
                'updated_at' => '2021-06-16 17:23:10',
            ],
            [
                'id' => 18,
                'kode_unit_kerja' => 'D1B',
                'nama_unit_kerja' => 'Ilmu Perpustakaan Dan Sains Informasi',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ilmu Sosial dan Politik',
                'created_at' => '2021-06-16 17:18:33',
                'updated_at' => '2023-02-21 08:41:02',
            ],
            [
                'id' => 19,
                'kode_unit_kerja' => 'D1C',
                'nama_unit_kerja' => 'Jurnalistik',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ilmu Sosial dan Politik',
                'created_at' => '2021-06-16 17:04:57',
                'updated_at' => '2021-06-16 17:04:57',
            ],
            [
                'id' => 20,
                'kode_unit_kerja' => 'D1D',
                'nama_unit_kerja' => 'Administrasi Publik',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ilmu Sosial dan Politik',
                'created_at' => '2021-06-16 17:18:03',
                'updated_at' => '2021-06-16 19:56:14',
            ],
            [
                'id' => 21,
                'kode_unit_kerja' => 'D1E',
                'nama_unit_kerja' => 'Ilmu Komunikasi',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ilmu Sosial dan Politik',
                'created_at' => '2021-06-16 17:17:16',
                'updated_at' => '2021-06-16 17:17:16',
            ],
            [
                'id' => 22,
                'kode_unit_kerja' => 'D1F',
                'nama_unit_kerja' => 'Sosiologi',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ilmu Sosial dan Politik',
                'created_at' => '2021-06-16 17:16:54',
                'updated_at' => '2021-06-16 17:16:54',
            ],
            [
                'kode_asal' => 'D2A',
                'nama_asal' => 'S2 KESEJAHTERAAN SOSIAL',
                'jenis' => 'Prodi',
                'created_at' => '2021-07-13 11:06:55',
                'updated_at' => '2021-07-13 11:06:55',
            ],
            [
                'kode_asal' => 'D2B',
                'nama_asal' => 'S2 ADMINISTRASI PUBLIK',
                'jenis' => 'Prodi',
                'created_at' => '2021-07-13 11:07:17',
                'updated_at' => '2021-07-13 11:07:17',
            ],
            [
                'kode_asal' => 'D2C',
                'nama_asal' => 'S2 ILMU KOMUNIKASI',
                'jenis' => 'Prodi',
                'created_at' => '2021-07-13 11:07:43',
                'updated_at' => '2021-07-13 11:07:43',
            ],
            [
                'kode_asal' => 'D0A',
                'nama_asal' => 'D3 ADMINISTRASI PERKANTORAN',
                'jenis' => 'Prodi',
                'created_at' => '2023-02-06 14:24:22',
                'updated_at' => '2023-02-06 14:24:22',
            ],
            [
                'kode_asal' => 'D0B',
                'nama_asal' => 'D3 PERPUSTAKAAN',
                'jenis' => 'Prodi',
                'created_at' => '2023-02-06 14:25:13',
                'updated_at' => '2023-02-06 14:25:13',
            ],
            [
                'kode_asal' => 'D0C',
                'nama_asal' => 'D3 JURNALISTIK',
                'jenis' => 'Prodi',
                'created_at' => '2023-02-21 08:54:28',
                'updated_at' => '2023-02-21 08:54:28',
            ],
            [
                'id' => 23,
                'kode_unit_kerja' => 'E',
                'nama_unit_kerja' => 'Pertanian',
                'jenis_unit_kerja' => 'Fakultas',
                'jenjang' => null,
                'fakultas' => 'Fakultas Pertanian',
                'created_at' => '2021-06-16 17:13:25',
                'updated_at' => '2021-06-16 17:13:25',
            ],
            [
                'id' => 24,
                'kode_unit_kerja' => 'E1B',
                'nama_unit_kerja' => 'Kehutanan',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Pertanian',
                'created_at' => '2021-06-16 17:05:22',
                'updated_at' => '2021-06-16 17:05:22',
            ],
            [
                'id' => 25,
                'kode_unit_kerja' => 'E1C',
                'nama_unit_kerja' => 'Peternakan',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Pertanian',
                'created_at' => '2021-06-16 17:02:28',
                'updated_at' => '2021-06-16 17:02:28',
            ],
            [
                'id' => 26,
                'kode_unit_kerja' => 'E1D',
                'nama_unit_kerja' => 'Agribisnis',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Pertanian',
                'created_at' => '2021-06-16 16:56:06',
                'updated_at' => '2021-06-16 16:56:06',
            ],
            [
                'id' => 27,
                'kode_unit_kerja' => 'E1G',
                'nama_unit_kerja' => 'Teknologi Industri Pertanian',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Pertanian',
                'created_at' => '2021-06-16 17:01:51',
                'updated_at' => '2021-06-16 17:01:51',
            ],
            [
                'id' => 28,
                'kode_unit_kerja' => 'E1I',
                'nama_unit_kerja' => 'Ilmu Kelautan',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Pertanian',
                'created_at' => '2021-06-16 17:01:14',
                'updated_at' => '2021-06-16 17:01:14',
            ],
            [
                'id' => 29,
                'kode_unit_kerja' => 'E1J',
                'nama_unit_kerja' => 'Agroekoteknologi',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Pertanian',
                'created_at' => '2021-06-16 16:56:40',
                'updated_at' => '2021-06-16 16:56:40',
            ],
            [
                'id' => 30,
                'kode_unit_kerja' => 'E1K',
                'nama_unit_kerja' => 'Proteksi Tanaman',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Pertanian',
                'created_at' => '2021-06-16 17:00:39',
                'updated_at' => '2021-06-16 17:00:39',
            ],
            [
                'kode_asal' => 'E1L',
                'nama_asal' => 'S1 ILMU TANAH',
                'jenis' => 'Prodi',
                'created_at' => '2021-07-13 11:25:34',
                'updated_at' => '2021-07-13 11:25:34',
            ],
            [
                'kode_asal' => 'E2A',
                'nama_asal' => 'S2 PENGELOLAAN SUMBER DAYA ALAM',
                'jenis' => 'Prodi',
                'created_at' => '2021-07-13 11:26:23',
                'updated_at' => '2021-07-13 11:26:23',
            ],
            [
                'kode_asal' => 'E2B',
                'nama_asal' => 'S2 AGRIBISNIS',
                'jenis' => 'Prodi',
                'created_at' => '2021-07-13 11:26:41',
                'updated_at' => '2021-07-13 11:26:41',
            ],
            [
                'kode_asal' => 'E2C',
                'nama_asal' => 'S2 AGROEKOTEKNOLOGI',
                'jenis' => 'Prodi',
                'created_at' => '2021-07-13 11:26:59',
                'updated_at' => '2021-07-13 11:26:59',
            ],
            [
                'kode_asal' => 'E3A',
                'nama_asal' => 'S3 ILMU PERTANIAN',
                'jenis' => 'Prodi',
                'created_at' => '2021-07-13 11:27:18',
                'updated_at' => '2021-07-13 11:27:18',
            ],
            [
                'kode_asal' => 'E3B',
                'nama_asal' => 'S3 PENGELOLAAN SUMBER DAYA ALAM',
                'jenis' => 'Prodi',
                'created_at' => '2023-02-21 03:22:13',
                'updated_at' => '2023-02-21 03:22:31',
            ],
            [
                'id' => 31,
                'kode_unit_kerja' => 'F',
                'nama_unit_kerja' => 'Matematika dan Pengetahuan Alam',
                'jenis_unit_kerja' => 'Fakultas',
                'jenjang' => null,
                'fakultas' => 'Fakultas Matematika dan Pengetahuan Alam',
                'created_at' => '2021-06-16 17:14:33',
                'updated_at' => '2021-06-16 17:14:33',
            ],
            [
                'id' => 32,
                'kode_unit_kerja' => 'F1A',
                'nama_unit_kerja' => 'Matematika',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Matematika dan Pengetahuan Alam',
                'created_at' => '2021-06-16 17:16:29',
                'updated_at' => '2021-06-16 17:16:29',
            ],
            [
                'id' => 33,
                'kode_unit_kerja' => 'F1B',
                'nama_unit_kerja' => 'Kimia',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Matematika dan Pengetahuan Alam',
                'created_at' => '2021-06-16 17:15:53',
                'updated_at' => '2021-06-16 17:15:53',
            ],
            [
                'id' => 34,
                'kode_unit_kerja' => 'F1C',
                'nama_unit_kerja' => 'Fisika',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Matematika dan Pengetahuan Alam',
                'created_at' => '2021-06-16 17:00:09',
                'updated_at' => '2021-06-16 17:00:09',
            ],
            [
                'id' => 35,
                'kode_unit_kerja' => 'F1D',
                'nama_unit_kerja' => 'Biologi',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Matematika dan Pengetahuan Alam',
                'created_at' => '2021-06-16 16:59:47',
                'updated_at' => '2021-06-16 16:59:47',
            ],
            [
                'id' => 36,
                'kode_unit_kerja' => 'F1F',
                'nama_unit_kerja' => 'Statistika',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Matematika dan Pengetahuan Alam',
                'created_at' => '2021-06-16 17:16:10',
                'updated_at' => '2021-06-16 17:16:10',
            ],
            [
                'id' => 46,
                'kode_unit_kerja' => 'F1G',
                'nama_unit_kerja' => 'Farmasi',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Kedokteran',
                'created_at' => '2021-07-02 10:19:38',
                'updated_at' => '2021-07-02 10:19:38',
            ],
            [
                'id' => 47,
                'kode_unit_kerja' => 'F0I',
                'nama_unit_kerja' => 'Farmasi',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'D3',
                'fakultas' => 'Fakultas Kedokteran',
                'created_at' => '2021-07-02 10:20:03',
                'updated_at' => '2021-07-02 10:20:03',
            ],
            [
                'id' => 48,
                'kode_unit_kerja' => 'F0A',
                'nama_unit_kerja' => 'Kebidanan',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'D3',
                'fakultas' => 'Fakultas Kedokteran',
                'created_at' => '2021-07-02 10:25:40',
                'updated_at' => '2021-07-02 10:25:40',
            ],
            [
                'id' => 49,
                'kode_unit_kerja' => 'F0B',
                'nama_unit_kerja' => 'Keperawatan',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'D3',
                'fakultas' => 'Fakultas Kedokteran',
                'created_at' => '2021-07-02 10:25:52',
                'updated_at' => '2021-07-02 10:25:52',
            ],
            [
                'kode_asal' => 'F1H',
                'nama_asal' => 'S1 GEOFISIKA',
                'jenis' => 'Prodi',
                'created_at' => '2021-07-13 11:40:57',
                'updated_at' => '2021-07-13 11:40:57',
            ],
            [
                'kode_asal' => 'F0C',
                'nama_asal' => 'D3 LABORATORIUM SAINS',
                'jenis' => 'Prodi',
                'created_at' => '2021-07-13 11:42:16',
                'updated_at' => '2021-07-13 11:42:16',
            ],
            [
                'kode_asal' => 'F2A',
                'nama_asal' => 'S2 STATISTIKA',
                'jenis' => 'Prodi',
                'created_at' => '2021-07-13 11:43:30',
                'updated_at' => '2021-07-13 11:43:30',
            ],
            [
                'kode_asal' => 'F2B',
                'nama_asal' => 'S2 KIMIA',
                'jenis' => 'Prodi',
                'created_at' => '2021-07-13 11:43:41',
                'updated_at' => '2021-07-13 11:43:41',
            ],
            [
                'kode_asal' => 'F2C',
                'nama_asal' => 'S2 BIOLOGI',
                'jenis' => 'Prodi',
                'created_at' => '2023-02-21 03:24:14',
                'updated_at' => '2023-02-21 03:24:47',
            ],
            [
                'id' => 37,
                'kode_unit_kerja' => 'G',
                'nama_unit_kerja' => 'TEKNIK',
                'jenis_unit_kerja' => 'Fakultas',
                'jenjang' => null,
                'fakultas' => 'Fakultas Teknik',
                'created_at' => '2021-06-16 17:10:21',
                'updated_at' => '2021-06-16 17:10:21',
            ],
            [
                'id' => 38,
                'kode_unit_kerja' => 'G1A',
                'nama_unit_kerja' => 'Informatika',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Teknik',
                'created_at' => '2021-06-08 08:01:21',
                'updated_at' => '2021-06-16 14:04:33',
            ],
            [
                'id' => 39,
                'kode_unit_kerja' => 'G1B',
                'nama_unit_kerja' => 'Teknik Sipil',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Teknik',
                'created_at' => '2021-06-08 08:01:38',
                'updated_at' => '2021-06-08 08:03:09',
            ],
            [
                'id' => 40,
                'kode_unit_kerja' => 'G1C',
                'nama_unit_kerja' => 'Teknik Mesin',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Teknik',
                'created_at' => '2021-06-08 08:01:52',
                'updated_at' => '2021-06-08 08:03:16',
            ],
            [
                'id' => 41,
                'kode_unit_kerja' => 'G1D',
                'nama_unit_kerja' => 'Teknik Elektro',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Teknik',
                'created_at' => '2021-06-08 08:02:15',
                'updated_at' => '2021-06-08 08:03:25',
            ],
            [
                'id' => 42,
                'kode_unit_kerja' => 'G1E',
                'nama_unit_kerja' => 'Arsitektur',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Teknik',
                'created_at' => '2021-06-08 08:02:28',
                'updated_at' => '2021-06-16 23:38:59',
            ],
            [
                'id' => 43,
                'kode_unit_kerja' => 'G1F',
                'nama_unit_kerja' => 'Sistem Informasi',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Teknik',
                'created_at' => '2021-06-08 08:03:02',
                'updated_at' => '2021-06-08 08:03:02',
            ],
            [
                'id' => 44,
                'kode_unit_kerja' => 'H',
                'nama_unit_kerja' => 'KEDOKTERAN',
                'jenis_unit_kerja' => 'Fakultas',
                'jenjang' => null,
                'fakultas' => 'Fakultas Kedokteran',
                'created_at' => '2021-06-16 17:15:08',
                'updated_at' => '2021-07-02 09:36:13',
            ],
            [
                'id' => 45,
                'kode_unit_kerja' => 'H1A',
                'nama_unit_kerja' => 'Pendidikan Dokter',
                'jenis_unit_kerja' => 'prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Kedokteran',
                'created_at' => '2021-06-16 17:15:33',
                'updated_at' => '2021-06-16 17:15:33',
            ],
            [
                'kode_asal' => 'H1B',
                'nama_asal' => 'PROFESI DOKTER',
                'jenis' => 'Prodi',
                'created_at' => '2021-08-14 18:14:41',
                'updated_at' => '2021-08-14 18:14:41',
            ]
        ];

        foreach ($data as &$item) {
            unset($item['id']);
        }

        UnitKerja::insert($data);
    }
}
