<?php

namespace Database\Seeders;

use App\Models\UnitKerja;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UnitKerjaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['id' => 1,  'kode_unit_kerja' => 'A',   'nama_unit_kerja' => 'Keguruan dan Ilmu Pendidikan',         'jenis_unit_kerja' => 'Fakultas', 'jenjang' => null, 'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2,  'kode_unit_kerja' => 'A1A', 'nama_unit_kerja' => 'Pendidikan Bahasa Indonesia',           'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3,  'kode_unit_kerja' => 'A1B', 'nama_unit_kerja' => 'Pendidikan Bahasa Inggris',             'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4,  'kode_unit_kerja' => 'A1C', 'nama_unit_kerja' => 'Pendidikan Matematika',                 'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5,  'kode_unit_kerja' => 'A1D', 'nama_unit_kerja' => 'Pendidikan Biologi',                    'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6,  'kode_unit_kerja' => 'A1E', 'nama_unit_kerja' => 'Pendidikan Fisika',                     'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7,  'kode_unit_kerja' => 'A1F', 'nama_unit_kerja' => 'Pendidikan Kimia',                      'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8,  'kode_unit_kerja' => 'A1G', 'nama_unit_kerja' => 'Pendidikan Guru Sekolah Dasar',         'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 9,  'kode_unit_kerja' => 'A1I', 'nama_unit_kerja' => 'Pendidikan Guru Paud',                  'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 10, 'kode_unit_kerja' => 'A1J', 'nama_unit_kerja' => 'Pendidikan Non Formal',                 'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 11, 'kode_unit_kerja' => 'A1L', 'nama_unit_kerja' => 'Bimbingan dan Konseling',               'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            [
                'id' => 50,
                'kode_unit_kerja' => 'A1M',
                'nama_unit_kerja' => 'Pendidikan Jasmani',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:38:11',
                'updated_at' => '2021-07-12 16:38:11',
            ],
            [
                'id' => 51,
                'kode_unit_kerja' => 'A1N',
                'nama_unit_kerja' => 'Pendidikan IPA',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:40:43',
                'updated_at' => '2021-07-12 16:40:43',
            ],
            [
                'id' => 52,
                'kode_unit_kerja' => 'A01',
                'nama_unit_kerja' => 'Bahasa Inggris',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'D3',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:45:10',
                'updated_at' => '2021-07-12 16:45:10',
            ],
            [
                'id' => 53,
                'kode_unit_kerja' => 'A2A',
                'nama_unit_kerja' => 'Pendidikan Bahasa Indonesia',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:46:41',
                'updated_at' => '2021-07-12 16:46:41',
            ],
            [
                'id' => 54,
                'kode_unit_kerja' => 'A2B',
                'nama_unit_kerja' => 'Teknologi Pendidikan',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:47:08',
                'updated_at' => '2021-07-12 16:47:08',
            ],
            [
                'id' => 55,
                'kode_unit_kerja' => 'A2C',
                'nama_unit_kerja' => 'Pendidikan Dasar',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:47:33',
                'updated_at' => '2021-07-12 16:47:33',
            ],
            [
                'id' => 56,
                'kode_unit_kerja' => 'A2D',
                'nama_unit_kerja' => 'Administrasi Pendidikan',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:47:57',
                'updated_at' => '2021-07-12 16:47:57',
            ],
            [
                'id' => 57,
                'kode_unit_kerja' => 'A2E',
                'nama_unit_kerja' => 'Pendidikan Bahasa Inggris',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:48:25',
                'updated_at' => '2021-07-12 16:48:25',
            ],
            [
                'id' => 58,
                'kode_unit_kerja' => 'A2F',
                'nama_unit_kerja' => 'Pendidikan Matematika',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:48:57',
                'updated_at' => '2021-07-12 16:48:57',
            ],
            [
                'id' => 59,
                'kode_unit_kerja' => 'A2G',
                'nama_unit_kerja' => 'Pendidikan IPA',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:49:18',
                'updated_at' => '2021-07-12 16:49:18',
            ],
            [
                'kode_asal' => 'A3',
                'nama_asal' => 'S3 LINGUISTIK TERAPAN',
                'jenis' => 'Prodi',
                'created_at' => '2023-10-23 19:11:45',
                'updated_at' => '2023-10-23 19:11:45',
            ],
            [
                'id' => 60,
                'kode_unit_kerja' => 'A3A',
                'nama_unit_kerja' => 'Pendidikan',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S3',
                'fakultas' => 'Fakultas Pendidikan',
                'created_at' => '2021-07-12 16:49:38',
                'updated_at' => '2021-07-12 16:49:38',
            ],
            [
                'kode_asal' => 'A4A',
                'nama_asal' => 'PROFESI PENDIDIKAN PROFESI GURU',
                'jenis' => 'Prodi',
                'created_at' => '2023-02-21 03:29:00',
                'updated_at' => '2023-02-21 03:29:00',
            ],
            [
                'id' => 61,
                'kode_unit_kerja' => 'B2A',
                'nama_unit_kerja' => 'Ilmu Hukum',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Hukum',
                'created_at' => '2021-07-13 10:47:34',
                'updated_at' => '2021-07-13 10:47:34',
            ],
            [
                'id' => 62,
                'kode_unit_kerja' => 'B2B',
                'nama_unit_kerja' => 'Kenotariatan',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S2',
                'fakultas' => 'Fakultas Hukum',
                'created_at' => '2021-07-13 10:47:54',
                'updated_at' => '2021-07-13 10:47:54',
            ],

            [
                'id' => 12,
                'kode_unit_kerja' => 'C',
                'nama_unit_kerja' => 'Ekonomi Dan Bisnis',
                'jenis_unit_kerja' => 'Fakultas',
                'jenjang' => null,
                'fakultas' => 'Fakultas Ekonomi dan Bisnis',
                'created_at' => '2021-06-16 17:11:25',
                'updated_at' => '2021-06-16 17:11:25',
            ],
            [
                'id' => 13,
                'kode_unit_kerja' => 'C1A',
                'nama_unit_kerja' => 'Ekonomi Pembangunan',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ekonomi dan Bisnis',
                'created_at' => '2021-06-16 17:18:58',
                'updated_at' => '2021-06-16 17:18:58',
            ],
            [
                'id' => 14,
                'kode_unit_kerja' => 'C1B',
                'nama_unit_kerja' => 'Manajemen',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ekonomi dan Bisnis',
                'created_at' => '2021-06-16 17:04:35',
                'updated_at' => '2021-06-16 17:04:35',
            ],
            [
                'id' => 15,
                'kode_unit_kerja' => 'C1C',
                'nama_unit_kerja' => 'Akuntansi',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ekonomi dan Bisnis',
                'created_at' => '2021-06-16 16:57:20',
                'updated_at' => '2021-06-16 16:57:20',
            ],
            [
                'id' => 63,
                'kode_unit_kerja' => 'C0A',
                'nama_unit_kerja' => 'Akuntansi',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'D3',
                'fakultas' => 'Fakultas Ekonomi',
                'created_at' => '2021-07-13 10:51:44',
                'updated_at' => '2021-07-13 10:51:44',
            ],

        ];

        UnitKerja::insert($data);
    }
}
