<?php

namespace Database\Seeders;

use App\Models\UnitKerja;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UnitKerjaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['id' => 1,  'kode_unit_kerja' => 'A',   'nama_unit_kerja' => 'Keguruan dan Ilmu Pendidikan',         'jenis_unit_kerja' => 'Fakultas', 'jenjang' => null, 'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2,  'kode_unit_kerja' => 'A1A', 'nama_unit_kerja' => 'Pendidikan Bahasa Indonesia',           'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3,  'kode_unit_kerja' => 'A1B', 'nama_unit_kerja' => 'Pendidikan Bahasa Inggris',             'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4,  'kode_unit_kerja' => 'A1C', 'nama_unit_kerja' => 'Pendidikan Matematika',                 'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5,  'kode_unit_kerja' => 'A1D', 'nama_unit_kerja' => 'Pendidikan Biologi',                    'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6,  'kode_unit_kerja' => 'A1E', 'nama_unit_kerja' => 'Pendidikan Fisika',                     'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7,  'kode_unit_kerja' => 'A1F', 'nama_unit_kerja' => 'Pendidikan Kimia',                      'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8,  'kode_unit_kerja' => 'A1G', 'nama_unit_kerja' => 'Pendidikan Guru Sekolah Dasar',         'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 9,  'kode_unit_kerja' => 'A1I', 'nama_unit_kerja' => 'Pendidikan Guru Paud',                  'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 10, 'kode_unit_kerja' => 'A1J', 'nama_unit_kerja' => 'Pendidikan Non Formal',                 'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 11, 'kode_unit_kerja' => 'A1L', 'nama_unit_kerja' => 'Bimbingan dan Konseling',               'jenis_unit_kerja' => 'Prodi',    'jenjang' => 'S1',  'fakultas' => 'Fakultas Keguruan Dan Ilmu Pendidikan', 'created_at' => now(), 'updated_at' => now()],
            [
                'id' => 12,
                'kode_unit_kerja' => 'C',
                'nama_unit_kerja' => 'Ekonomi Dan Bisnis',
                'jenis_unit_kerja' => 'Fakultas',
                'jenjang' => null,
                'fakultas' => 'Fakultas Ekonomi dan Bisnis',
                'created_at' => '2021-06-16 17:11:25',
                'updated_at' => '2021-06-16 17:11:25',
            ],
            [
                'id' => 13,
                'kode_unit_kerja' => 'C1A',
                'nama_unit_kerja' => 'Ekonomi Pembangunan',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ekonomi dan Bisnis',
                'created_at' => '2021-06-16 17:18:58',
                'updated_at' => '2021-06-16 17:18:58',
            ],
            [
                'id' => 14,
                'kode_unit_kerja' => 'C1B',
                'nama_unit_kerja' => 'Manajemen',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ekonomi dan Bisnis',
                'created_at' => '2021-06-16 17:04:35',
                'updated_at' => '2021-06-16 17:04:35',
            ],
            [
                'id' => 15,
                'kode_unit_kerja' => 'C1C',
                'nama_unit_kerja' => 'Akuntansi',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ekonomi dan Bisnis',
                'created_at' => '2021-06-16 16:57:20',
                'updated_at' => '2021-06-16 16:57:20',
            ],
            [
                'id' => 16,
                'kode_unit_kerja' => 'D',
                'nama_unit_kerja' => 'Ilmu Sosial Dan Politik',
                'jenis_unit_kerja' => 'Fakultas',
                'jenjang' => null,
                'fakultas' => 'Fakultas Ilmu Sosial dan Politik',
                'created_at' => '2021-06-16 17:12:59',
                'updated_at' => '2021-06-16 17:12:59',
            ],
            [
                'id' => 17,
                'kode_unit_kerja' => 'D1A',
                'nama_unit_kerja' => 'Ilmu Kesejahteraan Sosial',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ilmu Sosial dan Politik',
                'created_at' => '2021-06-16 17:23:10',
                'updated_at' => '2021-06-16 17:23:10',
            ],
            [
                'id' => 18,
                'kode_unit_kerja' => 'D1B',
                'nama_unit_kerja' => 'Ilmu Perpustakaan Dan Sains Informasi',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ilmu Sosial dan Politik',
                'created_at' => '2021-06-16 17:18:33',
                'updated_at' => '2023-02-21 08:41:02',
            ],
            [
                'id' => 19,
                'kode_unit_kerja' => 'D1C',
                'nama_unit_kerja' => 'Jurnalistik',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ilmu Sosial dan Politik',
                'created_at' => '2021-06-16 17:04:57',
                'updated_at' => '2021-06-16 17:04:57',
            ],
            [
                'id' => 20,
                'kode_unit_kerja' => 'D1D',
                'nama_unit_kerja' => 'Administrasi Publik',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ilmu Sosial dan Politik',
                'created_at' => '2021-06-16 17:18:03',
                'updated_at' => '2021-06-16 19:56:14',
            ],
            [
                'id' => 21,
                'kode_unit_kerja' => 'D1E',
                'nama_unit_kerja' => 'Ilmu Komunikasi',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ilmu Sosial dan Politik',
                'created_at' => '2021-06-16 17:17:16',
                'updated_at' => '2021-06-16 17:17:16',
            ],
            [
                'id' => 22,
                'kode_unit_kerja' => 'D1F',
                'nama_unit_kerja' => 'Sosiologi',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Ilmu Sosial dan Politik',
                'created_at' => '2021-06-16 17:16:54',
                'updated_at' => '2021-06-16 17:16:54',
            ],
            [
                'id' => 23,
                'kode_unit_kerja' => 'E',
                'nama_unit_kerja' => 'Pertanian',
                'jenis_unit_kerja' => 'Fakultas',
                'jenjang' => null,
                'fakultas' => 'Fakultas Pertanian',
                'created_at' => '2021-06-16 17:13:25',
                'updated_at' => '2021-06-16 17:13:25',
            ],
            [
                'id' => 24,
                'kode_unit_kerja' => 'E1B',
                'nama_unit_kerja' => 'Kehutanan',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Pertanian',
                'created_at' => '2021-06-16 17:05:22',
                'updated_at' => '2021-06-16 17:05:22',
            ],
            [
                'id' => 25,
                'kode_unit_kerja' => 'E1C',
                'nama_unit_kerja' => 'Peternakan',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Pertanian',
                'created_at' => '2021-06-16 17:02:28',
                'updated_at' => '2021-06-16 17:02:28',
            ],
            [
                'id' => 26,
                'kode_unit_kerja' => 'E1D',
                'nama_unit_kerja' => 'Agribisnis',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Pertanian',
                'created_at' => '2021-06-16 16:56:06',
                'updated_at' => '2021-06-16 16:56:06',
            ],
            [
                'id' => 27,
                'kode_unit_kerja' => 'E1G',
                'nama_unit_kerja' => 'Teknologi Industri Pertanian',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Pertanian',
                'created_at' => '2021-06-16 17:01:51',
                'updated_at' => '2021-06-16 17:01:51',
            ],
            [
                'id' => 28,
                'kode_unit_kerja' => 'E1I',
                'nama_unit_kerja' => 'Ilmu Kelautan',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Pertanian',
                'created_at' => '2021-06-16 17:01:14',
                'updated_at' => '2021-06-16 17:01:14',
            ],
            [
                'id' => 29,
                'kode_unit_kerja' => 'E1J',
                'nama_unit_kerja' => 'Agroekoteknologi',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Pertanian',
                'created_at' => '2021-06-16 16:56:40',
                'updated_at' => '2021-06-16 16:56:40',
            ],
            [
                'id' => 30,
                'kode_unit_kerja' => 'E1K',
                'nama_unit_kerja' => 'Proteksi Tanaman',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas Pertanian',
                'created_at' => '2021-06-16 17:00:39',
                'updated_at' => '2021-06-16 17:00:39',
            ],
            [
                'id' => 31,
                'kode_unit_kerja' => 'F',
                'nama_unit_kerja' => 'MIPA',
                'jenis_unit_kerja' => 'Fakultas',
                'jenjang' => null,
                'fakultas' => 'Fakultas MIPA',
                'created_at' => '2021-06-16 17:14:33',
                'updated_at' => '2021-06-16 17:14:33',
            ],
            [
                'id' => 32,
                'kode_unit_kerja' => 'F1A',
                'nama_unit_kerja' => 'Matematika',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas MIPA',
                'created_at' => '2021-06-16 17:16:29',
                'updated_at' => '2021-06-16 17:16:29',
            ],
            [
                'id' => 33,
                'kode_unit_kerja' => 'F1B',
                'nama_unit_kerja' => 'Kimia',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas MIPA',
                'created_at' => '2021-06-16 17:15:53',
                'updated_at' => '2021-06-16 17:15:53',
            ],
            [
                'id' => 34,
                'kode_unit_kerja' => 'F1C',
                'nama_unit_kerja' => 'Fisika',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas MIPA',
                'created_at' => '2021-06-16 17:00:09',
                'updated_at' => '2021-06-16 17:00:09',
            ],
            [
                'id' => 35,
                'kode_unit_kerja' => 'F1D',
                'nama_unit_kerja' => 'Biologi',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas MIPA',
                'created_at' => '2021-06-16 16:59:47',
                'updated_at' => '2021-06-16 16:59:47',
            ],
            [
                'id' => 36,
                'kode_unit_kerja' => 'F1F',
                'nama_unit_kerja' => 'Statistika',
                'jenis_unit_kerja' => 'Prodi',
                'jenjang' => 'S1',
                'fakultas' => 'Fakultas MIPA',
                'created_at' => '2021-06-16 17:16:10',
                'updated_at' => '2021-06-16 17:16:10',
            ],

        ];

        UnitKerja::insert($data);
    }
}
